"""empty message

Revision ID: e2d4acca4559
Revises: ff53991570c5
Create Date: 2024-12-02 00:21:13.525644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d4acca4559'
down_revision = 'ff53991570c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('check_type', sa.String(length=50), nullable=False),
    sa.Column('specific_file', sa.String(length=255), nullable=True),
    sa.Column('custom_config', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.drop_table('check_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('check_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('sepecific_file', sa.VARCHAR(length=255), nullable=True),
    sa.Column('custom_config', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('task_record')
    # ### end Alembic commands ###
