"""Added CronJob model

Revision ID: 923e01a5880f
Revises: 47df9ea9fcc3
Create Date: 2025-02-20 03:23:46.413811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923e01a5880f'
down_revision = '47df9ea9fcc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('config_file', sa.String(length=255), nullable=True),
    sa.Column('minute', sa.String(length=5), nullable=True),
    sa.Column('hour', sa.String(length=5), nullable=True),
    sa.Column('day', sa.String(length=5), nullable=True),
    sa.Column('month', sa.String(length=5), nullable=True),
    sa.Column('weekday', sa.String(length=5), nullable=True),
    sa.Column('startup', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cron_job')
    # ### end Alembic commands ###
